# Generated by Django 5.2.7 on 2025-11-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sale_options_alter_saleitem_options_sale_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Cliente'),
        ),
    ]
