# Generated by Django 5.2.7 on 2025-11-04 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0005_alter_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='related_operation_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movement_related_operation', to='contenttypes.contenttype', verbose_name='Tipo da Operação Relacionada'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='related_operation_object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID da Operação Relacionada'),
        ),
    ]
