# Generated by Django 5.2.7 on 2025-11-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_stockmovement_related_operation_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='code',
            field=models.CharField(default=1, max_length=50, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('code', 'stock'), name='unique_code_per_company_stock'),
        ),
    ]
