# Generated by Django 5.2.7 on 2025-11-12 15:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_item_code_item_unique_code_per_company_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('CASH', 'Dinheiro'), ('PIX', 'Pix'), ('CARD', 'Cartão'), ('CREDIT', 'Crédito'), ('DEBIT', 'Débito'), ('MUMBUCA', 'Mumbuca')], max_length=10, verbose_name='Tipo de Pagamento')),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Quanto deste pagamento deveria cobrir da venda.', max_digits=10, verbose_name='Valor a Pagar')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('change', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Troco')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Pagamento de Venda',
                'verbose_name_plural': 'Pagamentos de Vendas',
                'db_table': 'sale_payment',
            },
        ),
    ]
