from .street_type import STREET_TYPE_CHOICES
from .marital_status import MARITAL_STATUS_CHOICES
from .skin_color import SKIN_COLOR_CHOICES
from .education_level import EDUCATION_LEVEL_CHOICES
from .gender_identity import GENDER_IDENTITY_CHOICES
from .employee_status import EMPLOYEE_STATUS_CHOICES
from .brazilian_driver_license_categories import BRAZILIAN_DRIVER_LICENSE_CATEGORIES_CHOICES
from apps.utils.choices.buyer_type import BUYER_TYPE_CHOICES